# Generated by Django 4.1.2 on 2023-04-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersMarket', '0002_product_imgtitel_product_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImg',
            field=models.FileField(upload_to='Media'),
        ),
    ]
