# Generated by Django 4.1.2 on 2023-04-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersMarket', '0003_alter_product_productimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImg',
            field=models.ImageField(upload_to='Media'),
        ),
    ]
