# Generated by Django 4.1.2 on 2023-04-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersMarket', '0004_alter_product_productimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='', max_length=50)),
                ('number', models.IntegerField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
