# Generated by Django 4.1.2 on 2023-04-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersMarket', '0005_farmardetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField(default='', max_length=10)),
                ('orderuser', models.CharField(default='', max_length=255)),
                ('orderaddress', models.CharField(default='', max_length=255)),
                ('number', models.IntegerField(default='', max_length=10)),
                ('amount', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
