# Generated by Django 4.1.2 on 2023-04-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersMarket', '0006_placeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='FarmerUsername',
            field=models.CharField(default='', max_length=255),
        ),
    ]
