# Generated by Django 4.1.2 on 2023-04-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersMarket', '0007_placeorder_farmerusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='productTitle',
            field=models.CharField(default='', max_length=150),
        ),
    ]
